apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-vault
  namespace: {{ .Values.namespace }}
spec:
  # Secret names are always required.
  secretName: {{ .Values.name }}-vault-tls
  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  # secretTemplate:
  #   annotations:
  #     my-secret-annotation-1: "foo"
  #     my-secret-annotation-2: "bar"
  #   labels:
  #     my-secret-label: foo
  duration: 167h
  renewBefore: 144h
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: {{ .Values.name }}.anubisdev.inday.io
  isCA: false
  privateKey:
    algorithm: RSA
    # encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - "{{ .Values.name }}-vault-0.{{ .Values.name }}-vault-internal.{{ .Values.namespace }}.svc.cluster.local"
    - "{{ .Values.name }}-vault-1.{{ .Values.name }}-vault-internal.{{ .Values.namespace }}.svc.cluster.local"
    - "{{ .Values.name }}-vault-2.{{ .Values.name }}-vault-internal.{{ .Values.namespace }}.svc.cluster.local"
    - "*.{{ .Values.name }}-vault-internal"
    - "{{ .Values.name }}.anubisdev.inday.io"
    - "{{ .Values.name }}-vault-active.{{ .Values.namespace }}.svc.cluster.local"
  # uris:
  #   - spiffe://cluster.local/ns/sandbox/sa/example
  ipAddresses:
    - 127.0.0.1
  # Issuer references are always required.
  issuerRef:
    name: vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: AWSPCAClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: awspca.cert-manager.io
