apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.name }}-ingress-route-tcp
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`{{ .Values.name }}.anubisdev.inday.io`)
    services:
    - name: {{ .Values.name }}-vault-active
      port: 8200
  tls:
    passthrough: true
